bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'
requirePragma: false
jsxSingleQuote: false
insertPragma: false
proseWrap: 'always'
htmlWhitespaceSensitivity: 'css'
embeddedLanguageFormatting: 'auto'
singleAttributePerLine: true
quoteProps: 'as-needed'
semi: true
singleQuote: true
trailingComma: 'es5'
