services:
  bluesky-website:
    image: bluesky-website:0.1.0
    hostname: bluesky-website-container
    container_name: bluesky-website
    env_file:
      - .env
    build:
      context: .
    ports:
      - 80:8000
